2024-11-16 17:14:36,542 | INFO | "test_challenge" выполнен успешно
2024-11-16 17:14:36,543 | WARNING | Неверный тип данных для объекта Runner
Имя может быть только строкой, передано int
2024-11-16 17:14:36,545 | WARNING | Traceback (most recent call last):
  File "C:\Users\Ирина\PycharmProjects\pythonProject\module_12\tests_12_4.py", line 78, in test_run
    runner = Runner(2)
             ^^^^^^^^^
  File "C:\Users\Ирина\PycharmProjects\pythonProject\module_12\tests_12_4.py", line 19, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int

2024-11-16 17:14:36,546 | WARNING | Неверная скорость для Runner
Скорость не может быть отрицательной, сейчас -5
2024-11-16 17:14:36,567 | WARNING | Traceback (most recent call last):
  File "C:\Users\Ирина\PycharmProjects\pythonProject\module_12\tests_12_4.py", line 67, in test_walk
    runner = Runner("Вася", -5)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ирина\PycharmProjects\pythonProject\module_12\tests_12_4.py", line 24, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5

